sudo: required

services:
- docker

env:
  global:
  - secure: f9OBjqNo9l2hik0C/0W1/+57zCbgWt+dOW8XWpgBzch3IzHqnjHJarYqx178CTKLW5/bTPPKjcWuxIu4xeiQ1aJNsTxuMb+v+PISm1a60Fipz8HTC+URyeBXbrgspv7B/w9PB5Rp4ndGgODfXTogJqKrFyx+Deq4qgCMAO1K7ltwirwzKfmWDM0dNbV8BSydKDhkQwQVVLr9FonbsqxjMco0ur5+jiMCTrnxORt9jEfS736aWJYA/ipN8VN3GJWc7+k7sJZZV3oXdUs8bsN8fb4MleKP4SX0TT5k/h+AuWFqWClDkmaIdOwHjX8tX85HF5c7tTT2varNodDDBe3qojFCFetXiRAieHh/UBzfJPHMGSTOfFjIi6Ee16mWdQrTqE7XAw2OKG8HDMAUcZDps0IlWwIx5RRdUw0pJVYBmtr3hwZG09sf2c4WZZnPitVsY3vNGONoK+0DL94vF2mKDYukLa7biZ6WNDPL92OI+eWbK1wPPAK8nOu3jaiwzUrHy0TG85+KQrwQzxWbBIr2NT1Ez7HuQhIZXGQ8uAVQbPqVYCcFAkLfFs7ITEAZ+uTJx1ln3wibg7Nf47RuZ9n1SwNztMiNq4+1xGUtEKJkFA5kzPs4nQ2jFkhyOIc7CfiHZ9fTW/56NNFt9GUlGMJOREOME5yaVMkVuf8UdlumrF8= # DOCKER_USERNAME
  - secure: l0jTtTyX7ZSnDfxXHqmxPf3St3qGPMDpO9CK4vA5BzCFd7uURP9BKya4hOkGp5nBXkPWXQbgHPh6YXd9LEbXOnbImuSwzGZkarRUfo15lxmXGCu4I6AZLkjLqJld8D5FpGoJm74YqpTvxdfcDSaZ44IvwXnX9rWvA2m9g45bKu4fb55BGv+Kb4cxfOT7s+itDCkdjr6IYLRZ3x7L1yJHvIWuCj70Mbq4mbPxS2IbAZRrxlSjlCfvWzMFElGhkqCxyshNTffrpZiQd4LtPsppU+ibEVzzX6v+n/7KXsjgdewcQ2oU3RmOiuO77+a7P/iA76AFQWwfCFKFLOJjZBbgZpJcC94BrDrmPPnGrlPw3peEqk9vkYYb0gWnraOyC90pZ6rl0/WAQ1k05AbhPuix80qce1iX52GOVwwI2o+tqaVVK8YKkBkfKKA/eS89jF65zIsnZWWsO9R4CIVzl/B6MeL44NLwpqv6tFIGSgWDGDVHXtDMzmdEnd9BLfnwYfPthyawpPML3AgdOdG0kkXWFFLpDEFLzq/SrH/V9xOQ0frPlHvhnAWqGy/zHXY/IecL+dEwkG2ugWvtvt75s3scGst14LavwDCUr6fs3EqQdNoW7umXLaDtDeESxyLrYmu2CDHRYtTJTYIKic3ZE638QGSoMeh/leE18kEvdrRKJ3M= # DOCKER_PASSWORD

before_install:
- docker pull ubuntu:20.04
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD

script:
- "./build.sh shakataganai/miniubuntu"

notifications:
  email: false
  slack: false
